spring:
  batch:
    jdbc:
      initialize-schema: never
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: validate
  datasource:
    url: jdbc:mariadb://localhost:12345/dfdb?autoReconnect=true&useUnicode=true&characterEncoding=UTF8MB4
    driver-class-name: org.mariadb.jdbc.Driver
    username: manager
    password: managerPassword
    hikari:
      maximum-pool-size: 10
management:
  info:
    git:
      mode: full
    java:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
