spring:
  main:
    web-application-type: none
  batch:
    jdbc:
      initialize-schema: never
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: none
  datasource:
    primary:
      jdbc-url: ${PRIMARY_DATASOURCE_URL}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${PRIMARY_DATASOURCE_USERNAME}
      password: ${PRIMARY_DATASOURCE_PASSWORD}
    batch:
      jdbc-url: ${BATCH_DATASOURCE_URL}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${BATCH_DATASOURCE_USERNAME}
      password: ${BATCH_DATASOURCE_PASSWORD}
